language: python
python:
#  - 3.5
#  - 3.6
  - 3.7
#  - nightly
addons:
  apt:
    packages:
    - python3-pip
before_install:
  - sudo pip3 install setuptools wheel
install:
  - sudo pip3 install .
before_script:
  - sudo pip3 install pytest pytest-tornado black
script:
  - pytest ngshare
#  - black -S -l 80 --check .
  - black -S -l 80 --check testing
after_success:
  - echo AFTER_SUCCESS
