# Override the ngshare name, if you want to
nameOverride: ""
fullnameOverride: ""

# Where to pull the ngshare image
image: 
  repository: rkevin/ngshare
  version: latest
  pullPolicy: IfNotPresent
  imagePullSecrets: []

# Configure the deployment and service
deployment:
  # Numbers of ngshare replicas to make
  # WARNING: Anything greater than 1 is not tested
  replicaCount: 1

  # Port to expose on the ClusterIP service. Shouldn't matter that much.
  port: 8080

  # Add group permissions to read/write to the PV
  fsGroup: 1000

  # Resource limitations for the pod
  resources: {}
    # Define like this:
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # Additional stuff that might be useful when you're configuring things
  selectorLabels: []
  nodeSelector: {}
  tolerations: []
  affinity: {}


# Configure environment / cmdline passed to ngshare
ngshare:
  # JupyterHub API url, without the trailing slash
  # If you didn't modify the Z2JH helm chart, this value should be right
  hub_api_url: http://hub:8081/hub/api

  # Not sure what this is, frankly, so leaving it configurable
  hub_base_url: /

  # API token to talk to the hub with
  # If left empty, a random one will be generated at install time
  hub_api_token: 

  # Additional environment variables
  env: {}

  # Additional cmdline arguments
  args: []

# PVC Storage to allocate to ngshare
pvc:
  # Amount of storage to allocate
  storage: 1Gi

  # Additional configs if you have custom needs like specifying a storageclass
  annotations: {}
  selector: {}
  storageClassName:
